export const ADD_INGREDIENT_FAILED: 'ADD_INGREDIENT_FAILED' = 'ADD_INGREDIENT_FAILED';
export const ADD_INGREDIENT_SUCCESS: 'ADD_INGREDIENTS_SUCCESS' = 'ADD_INGREDIENTS_SUCCESS';

export const ADD_BUN: 'ADD_BUN' = 'ADD_BUN';
export const ADD_BUN_FAILED: 'ADD_BUN_FAILED' = 'ADD_BUN_FAILED';
export const ADD_BUN_SUCCESS: 'ADD_BUN_SUCCESS' = 'ADD_BUN_SUCCESS';

export const REMOVE_INGREDIENT: 'REMOVE_INGREDIENT' = 'REMOVE_INGREDIENT';
export const REPLASE_INGREDIENTS: 'REPLASE_INGREDIENTS'='REPLASE_INGREDIENTS';

export const NEW_ORDER: 'NEW_ORDER' = 'NEW_ORDER';

export const BURGER_INGREDIENTS_REQUEST: 'BURGER_INGREDIENTS_REQUEST' = 'BURGER_INGREDIENTS_REQUEST';
export const BURGER_INGREDIENTS_REQUEST_SUCCESS: 'BURGER_INGREDIENTS_REQUEST_SUCCESS' = 'BURGER_INGREDIENTS_REQUEST_SUCCESS';
export const BURGER_INGREDIENTS_REQUEST_FAILED: 'BURGER_INGREDIENTS_REQUEST_FAILED' = 'BURGER_INGREDIENTS_REQUEST_FAILED';

export const BUN_INCREASER: 'BUN_INCREASER' = 'BUN_INCREASER';
export const OTHER_INGREDIENTS_INCREASER: 'OTHER_INGREDIENTS_INCREASER' = 'OTHER_INGREDIENTS_INCREASER';
export const INGREDIENT_COUNTER_DECREASE = 'INGREDIENT_COUNTER_DECREASE';
export const CLEAR_COUNTER: 'CLEAR_COUNTER' = 'CLEAR_COUNTER';

export const GETTING_ORDER_DETAILS: 'GETTING_ORDER_DETAILS' = 'GETTING_ORDER_DETAILS';
export const GET_ORDER_DETAILS_SUCCESS: 'GET_ORDER_DETAILS_SUCCESS' = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAILED: 'GET_ORDER_DETAILS_FAILED' = 'GET_ORDER_DETAILS_FAILED';
export const CLOSE_ORDER_DETAILS = 'CLOSE_ORDER_DETAILS';

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS: 'LOGIN_REQUEST_SUCCESS' = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILED: 'LOGIN_REQUEST_FAILED' = 'LOGIN_REQUEST_FAILED';

export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST';
export const REGISTER_REQUEST_SUCCESS: 'REGISTER_REQUEST_SUCCESS' = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILED: 'REGISTER_REQUEST_FAILED' = 'REGISTER_REQUEST_FAILED';

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS: 'LOGOUT_REQUEST_SUCCESS' = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILED: 'LOGOUT_REQUEST_FAILED' = 'LOGOUT_REQUEST_FAILED';

export const GET_USER_DATA: 'GET_USER_DATA' = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS' = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILED: 'GET_USER_DATA_FAILED' = 'GET_USER_DATA_FAILED';

export const UPDATE_USER_DATA: 'UPDATE_USER_DATA' = 'UPDATE_USER_DATA';
export const UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS' = 'UPDATE_USER_DATA_SUCCESS';
export const UPDATE_USER_DATA_FAILED: 'UPDATE_USER_DATA_FAILED' = 'UPDATE_USER_DATA_FAILED';
