export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS'; 
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';

export const WS_CONNECTION_START_PROTECTED: 'WS_CONNECTION_START_PROTECTED' = 'WS_CONNECTION_START_PROTECTED';
export const WS_CONNECTION_SUCCESS_PROTECTED: 'WS_CONNECTION_SUCCESS_PROTECTED' = 'WS_CONNECTION_SUCCESS_PROTECTED'; 
export const WS_CONNECTION_ERROR_PROTECTED: 'WS_CONNECTION_ERROR_PROTECTED' = 'WS_CONNECTION_ERROR_PROTECTED';
export const WS_CONNECTION_CLOSED_PROTECTED: 'WS_CONNECTION_CLOSED_PROTECTED' = 'WS_CONNECTION_CLOSED_PROTECTED';
export const WS_GET_MESSAGE_PROTECTED: 'WS_GET_MESSAGE_PROTECTED' = 'WS_GET_MESSAGE_PROTECTED';